# Generated by Django 4.2.7 on 2024-02-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='Travel_places',
        ),
    ]
